services:
  - type: web
    name: silentsos
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_4wbWrnqgNc3V@ep-cool-grass-aorbu4fo-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        value: harshavardhanreddy1910848@gmail.com
      - key: SMTP_PASS
        value: jlfkbhskzsmnhppv
      - key: FRONTEND_URL
        sync: false
      - key: APP_URL
        sync: false
